name: app_farmacia
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  

  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/Image/creatina.jpeg
    - assets/Image/omega3.jpeg
    - assets/Image/google.jpeg
    - assets/Image/dipirona.png
    - assets/Image/omega3.png
    - assets/Image/vitamina_c_sf.png
    - assets/Image/dorflex.png
    - assets/Image/expec.png
    - assets/Image/benegripe.png
    
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

  uses-material-design: true